// SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Button, IconButton, TextSm } from "@ui/widgets.slint";
import { Importance, Size, Palette } from "@ui/theme.slint";
import { TR2, TrId } from "../gen/tr.slint";
import { PickerGlobal } from "./global.slint";
import { FileList, FileListLoading, FileListType } from "../file-list.slint";
import { LocationSwitcher } from "../location-switcher.slint";

export component PickerBody inherits Rectangle {
    FileList {
        padding-left: Size.sz6;
        padding-right: Size.sz6;
        file-list: PickerGlobal.file-lists[PickerGlobal.location-idx];
        is-select-mode: false;
        are-files-allowed: !PickerGlobal.is-dir-selection-mode;
        are-folders-allowed: PickerGlobal.is-folders-allowed;
        long-press-enabled: false;
        compact-airlock-usb: true;

        entry-pressed(name, is-folder) => {
            PickerGlobal.entry-pressed(name, is-folder);
        }

        header := Rectangle {
            vertical-stretch: 0;
            HorizontalLayout {
                alignment: start;
                VerticalLayout {
                    alignment: center;
                    IconButton {
                        icon: "chevron-left";
                        importance: Importance.tertiary;
                        icon-color: Palette.content-primary;
                        visible: self.enabled;
                        enabled: PickerGlobal.current-path != "";
                        clicked => {
                            PickerGlobal.back();
                        }
                    }
                }
            }
        }
    }

    if PickerGlobal.is-dir-selection-mode: HorizontalLayout {
        y: parent.height - Size.sz8 - self.height;
        alignment: center;

        VerticalLayout {
            alignment: end;

            Button {
                width: 256px;
                label: TR2.lookup(TrId.CommonButtonSave);
                importance: Importance.primary;
                enabled: PickerGlobal.file-lists[PickerGlobal.location-idx].list-type == FileListType.FileList;
                clicked => {
                    PickerGlobal.select-directory();
                }
            }
        }
    }

    Rectangle {
        TouchArea {
            enabled: locations.menu-open;
            clicked => {
                locations.menu-open = false;
            }
        }

        locations := LocationSwitcher {
            x: header.absolute-position.x - root.absolute-position.x + (header.width - self.width) / 2;
            y: header.absolute-position.y - root.absolute-position.y + (header.height - self.height) / 2;
            locations: PickerGlobal.allowed-locations;
            selected_index: PickerGlobal.location-idx;
            breadcrumbs: PickerGlobal.build-breadcrumbs(PickerGlobal.location-idx, PickerGlobal.current-path);
            location-changed(index) => {
                PickerGlobal.location-changed(index);
            }
            breadcrumb-selected(name, index) => {
                PickerGlobal.breadcrumb-selected(name, index);
            }
        }
    }
}
