manifestVersion = "0"
appId = "0x6775692d6170702d63616d6572610000"
memory = ["ISC"]
syscall = ["ClaimInterrupt", "VirtToPhys", "MirrorMemoryToPid"]
extends = "../../api/camera"

[appName]
en = "Camera"

[servers."os/camera"]
SubscriberDisconnected = { id = 30, type = "scalar", cfg = "keyos" }
FrameCaptured = { id = 31, type = "scalar", cfg = "keyos" }

[permissions]
"template" = ["i2c", "gpio"]
"os/power-manager" = ["SetPeripheralEnabled"]
"os/settings" = ["SubscribeCameraEnabled"]
