# SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "usb-debug"
version = "0.1.0"
edition = "2021"

[features]
default = []
## Set by the build system for production firmware builds.
## Produces a compile error to prevent this crate from being included in production.
production = []

[dependencies]
gui-server-api = { workspace = true }
log = { workspace = true }
log-server = { workspace = true }
power-manager = { workspace = true }
rkyv = { workspace = true }
security = { workspace = true }
server = { workspace = true }
usb = { workspace = true }
usb-debug-protocol = { workspace = true }
utralib = { workspace = true }
uuid = "1.10"
xous = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(keyos)'] }
