manifestVersion = "0"
[servers."os/usb"]
Subscribe = { id = 1, type = "archiveEvent" }
Claim = { id = 2, type = "blockingScalar" }
OpenEndpoint = { id = 3, type = "blockingScalar" }
BulkOut = { id = 4, type = "deferredLendMut" }
BulkIn = { id = 5, type = "deferredLendMut" }
SetEnabled = { id = 6, type = "scalar" }
IsEnabled = { id = 7, type = "blockingScalar" }
IsConnected = { id = 8, type = "blockingScalar" }

[servers."os/usbdev"]
RegisterInterface = { id = 0, type = "blockingArchive" }
WaitForConnection = { id = 1, type = "blockingScalar" }
SetEndpointStalled = { id = 2, type = "scalar" }
ReadEndpoint = { id = 3, type = "deferredLendMut" }
WriteEndpoint = { id = 4, type = "deferredLendMut" }
NumInterfaces = { id = 7, type = "blockingScalar" }
RegisterSetupResponder = { id = 8, type = "blockingScalar" }
IsDeviceEmulationEnabled = { id = 9, type = "blockingScalar" }
IsDeviceEmulationConnected = { id = 10, type = "blockingScalar" }
RegisterCapability = { id = 11, type = "blockingArchive" }
SetVidPid = { id = 12, type = "scalar" }
ResetController = { id = 13, type = "blockingScalar" }
IsCableConnected = { id = 14, type = "blockingScalar" }
IsDeviceMode = { id = 15, type = "blockingScalar" }
SetupPacket = { id = 17, type = "scalar" }
