// SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { KeycardBackupPage } from "@ui/pages/keycard-backup/keycard-backup-page.slint";
import { KeycardBackupErrorDialog } from "@ui/pages/keycard-backup/keycard-backup-error.slint";
import { NavHeader, PageBody } from "@ui/widgets.slint";

import { Navigate } from "../../../../gen/navigate.slint";
import { TrId, TR2 } from "../../../../gen/tr.slint";
import { KeycardBackupGlobal } from "../../../../onboarding-callbacks.slint";
import { OnboardingBasePage } from "../../../../widgets/base-page.slint";

export component CreatingMagicBackupPage inherits OnboardingBasePage {
    VerticalLayout {
        NavHeader {
            left-icon: backup-page.backup-created ? "" : "chevron-left";

            clicked => {
                if !backup-page.backup-created {
                    Navigate.backward();
                }
            }
        }

        PageBody {
            alignment: stretch;
            backup-page := KeycardBackupPage {
                magic: true;
                steps: KeycardBackupGlobal.steps;
                saving-to-keycard: KeycardBackupGlobal.saving-to-keycard;

                header-text: self.backup-created ? TR2.lookup(TrId.KeycardBackupMagicCreatedHeader) : TR2.lookup(TrId.KeycardBackupMagicCreatingHeader);
                button-label: self.backup-created ? TR2.lookup(TrId.CommonButtonContinue) : TR2.lookup(TrId.CommonButtonCreating);

                start-backup => {
                    KeycardBackupGlobal.start-magic-backup();
                }
                continue => {
                    Navigate.connect-wallet({ });
                }
            }
        }
    }

    KeycardBackupErrorDialog {
        error: KeycardBackupGlobal.error;
        clicked(confirm) => {
            KeycardBackupGlobal.error-clicked(confirm);
        }
    }
}
