manifestVersion = "0"
appId = "0x6775692d6170702d6c61756e63686572"

[appName]
en = "App Launcher"

[permissions]
template = ["gui-app", "fs-generic"]
"os/app-manager" = ["SubscribeAppEvents", "GetAppName", "LaunchApp"]
"os/fs" = [
    "FormatEncryptedVolume",
    "SubscribeFilesystemEvent",
    "GetSystemAppDataReadAccess",
    "GetSystemAppDataWriteAccess",
]
"os/gui-server" = ["SwitchTo", "Shutdown", "NavigateTo", "UpdateKioskPolicy"]
"os/haptics" = ["Vibrate"]
"os/quantum-link" = ["SubscribeExchangeRate", "SubscribeExchangeRateHistory", "SubscribeConnectionStatus"]
"os/settings" = ["SetOnboardingStatus", "GetUseStandardTimeFormat", "GetTimeZone"]
"os/update" = ["ClearUpdateApplied", "GetUpdateApplied", "GetUpdateStatus", "SubscribeUpdateProgress"]
