// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Callbacks as CB } from "../../callbacks.slint";
import { Palette, Size } from "@ui/theme.slint";
import { Button, TextMd, HeadingMd, BasePage, ButtonSection, WrappedIcon, NavHeader, PageBody, ContentSection } from "@ui/widgets.slint";
import { ManualImportProps } from "./props.slint";
import { Navigate } from "../../gen/navigate.slint";
import { TR2, TrId } from "../../gen/tr.slint";

export component ManualImportPage inherits BasePage {
    in property <ManualImportProps> props;

    VerticalLayout {
        NavHeader {
            left-icon: "chevron-left";
            right-icon: "scan-qr";
            title: TR2.lookup(TrId.ImportItemManualImport);

            clicked => {
                Navigate.backward();
            }

            right-clicked => {
                CB.scan-qr();
            }
        }

        PageBody {
            padding-top: Size.sz4;

            ContentSection {
                HorizontalLayout {
                    alignment: center;
                    WrappedIcon {
                        inner-icon: "acorn";
                    }
                }

                VerticalLayout {
                    spacing: Size.sz5;
                    padding-left: Size.sz1;
                    padding-right: Size.sz1;

                    HeadingMd {
                        horizontal-alignment: center;
                        text: TR2.lookup(TrId.ManualImportHeader);
                        color: Palette.content-primary;
                    }

                    TextMd {
                        horizontal-alignment: center;
                        text: TR2.lookup(TrId.ManualImportSubheader);
                        color: Palette.content-secondary;
                    }
                }
            }

            ButtonSection {
                Button {
                    label: TR2.lookup(TrId.ManualImportImportSeedWords);
                    importance: secondary;
                    clicked => {
                        Navigate.input-seed({ });
                    }
                }

                Button {
                    label: TR2.lookup(TrId.ManualImportImportPassword);
                    importance: secondary;
                    clicked => {
                        Navigate.password({ });
                    }
                }
            }
        }
    }
}
