manifestVersion = "0"
appId = "0x7125fc9cbec5889fc16bd387cd382dd5"

[appName]
en = "async worker test"

[servers."test/worker-server"]
ArchiveIncrementTick = { id = 1, type = "blockingArchive" }
ScalarTickSub = { id = 2, type = "scalarEvent" }
ArchiveTickSub = { id = 3, type = "archiveEvent" }
Shutdown = { id = 4, type = "scalar" }
ArchiveDropAllSubs = { id = 5, type = "blockingArchive" }
ArchiveTick = { id = 6, type = "blockingArchive" }
ArchiveDrop = { id = 7, type = "blockingArchive" }
ScalarDoubleData = { id = 8, type = "blockingScalar" }
ScalarDropRequest = { id = 9, type = "blockingScalar" }
ScalarSubFallible = { id = 10, type = "scalarEvent" }
ArchiveSubFallible = { id = 11, type = "archiveEvent" }
ScalarInterval = { id = 12, type = "blockingScalar" }
HoldScalar = { id = 13, type = "blockingScalar" }
HeldScalarCount = { id = 14, type = "blockingScalar" }
ReleaseHeldScalars = { id = 15, type = "blockingScalar" }

[permissions]
"test/disposable" = ["ScalarEcho", "ShutdownDisposable", "HoldDisposableScalar"]

[servers."test/retry"]
RetryEcho = { id = 1, type = "blockingScalar" }
ShutdownRetry = { id = 2, type = "scalar" }
