manifestVersion = "0"
appId = "0x7379732d62656e63686d61726b000000"

[appName]
en = "mem-benchmark"

[servers."test/benchmark"]
Ping = { id = 0, type = "blockingScalar" }
AsyncPing = { id = 1, type = "scalar" }
MemPing = { id = 2, type = "lendMut" }
Shutdown = { id = 3, type = "scalar" }

[permissions]
"os/power-manager" = ["SetPeripheralEnabled"]
