// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Palette, Size, Utils, UISize } from "@ui/theme.slint";
import { Button, TextLg, Icon, JumboIcon, Shield, HeadingMd, TextMd, TimerCircularProgress, IconButton, Dialog, ButtonSection } from "@ui/widgets.slint";
import { TR2, TrId } from "../../gen/tr.slint";
import { KeycardBackupGlobal } from "../../onboarding-callbacks.slint";

component ErrorDialog inherits Dialog {
    icon: "alert";
    icon-color: Palette.content-notice;
    width: UISize.modal-width;
}

component Container inherits Rectangle {
    background: Palette.overlay;
}

export component KeycardBackupErrors {
    callback on-fatal-error();

    if KeycardBackupGlobal.saving-keycard-error: Container {
        Dialog {
            title: TR2.lookup(TrId.BackupModalErrorHeader);
            message: TR2.lookup(TrId.BackupModalErrorContent);
            ok-text: TR2.lookup(TrId.CommonButtonRetry);
            on-ok => {
                KeycardBackupGlobal.overwrite-keycard(false);
                KeycardBackupGlobal.clear-error();
            }
        }
    }

    if KeycardBackupGlobal.invalid-data-error: Container {
        ErrorDialog {
            title: TR2.lookup(TrId.BackupInvalidDataDetectedHeader);
            message: TR2.lookup(TrId.BackupInvalidDataDetectedContent);
            cancel-text: TR2.lookup(TrId.CommonButtonCancel);
            ok-text: TR2.lookup(TrId.CommonButtonOverwrite);
            show-cancel: true;
            on-ok => {
                KeycardBackupGlobal.overwrite-keycard(true);
                KeycardBackupGlobal.clear-error();
            }
            on-cancel => {
                KeycardBackupGlobal.overwrite-keycard(false);
                KeycardBackupGlobal.clear-error();
            }
        }
    }

    if KeycardBackupGlobal.different-master-key-error: Container {
        ErrorDialog {
            title: TR2.lookup(TrId.BackupModalDataDetectedHeader);
            message: TR2.lookup(TrId.BackupModalDataDetectedContentMasterKey);
            cancel-text: TR2.lookup(TrId.CommonButtonCancel);
            ok-text: TR2.lookup(TrId.CommonButtonConfirm);
            show-cancel: true;
            on-ok => {
                KeycardBackupGlobal.overwrite-keycard(true);
                KeycardBackupGlobal.clear-error();
            }
            on-cancel => {
                KeycardBackupGlobal.overwrite-keycard(false);
                KeycardBackupGlobal.clear-error();
            }
        }
    }

    if KeycardBackupGlobal.different-device-id-error: Container {
        ErrorDialog {
            title: TR2.lookup(TrId.BackupModalDataDetectedHeader);
            message: TR2.lookup(TrId.BackupModalDataDetectedContentPrime);
            cancel-text: TR2.lookup(TrId.CommonButtonCancel);
            ok-text: TR2.lookup(TrId.CommonButtonConfirm);
            show-cancel: true;
            on-ok => {
                KeycardBackupGlobal.overwrite-keycard(true);
                KeycardBackupGlobal.clear-error();
            }
            on-cancel => {
                KeycardBackupGlobal.overwrite-keycard(false);
                KeycardBackupGlobal.clear-error();
            }
        }
    }

    if KeycardBackupGlobal.unauth-keycard-error: Container {
        ErrorDialog {
            title: TR2.lookup(TrId.BackupInvalidThirdPartyKeycardHeader);
            message: TR2.lookup(TrId.BackupInvalidThirdPartyKeycardContent);
            cancel-text: TR2.lookup(TrId.CommonButtonCancel);
            ok-text: TR2.lookup(TrId.CommonButtonIUnderstand);
            show-cancel: true;
            on-ok => {
                KeycardBackupGlobal.overwrite-keycard(true);
                KeycardBackupGlobal.clear-error();
            }
            on-cancel => {
                KeycardBackupGlobal.overwrite-keycard(false);
                KeycardBackupGlobal.clear-error();
            }
        }
    }

    if KeycardBackupGlobal.same-backup-confirmation: Container {
        ErrorDialog {
            title: TR2.lookup(TrId.BackupModalDataDetectedHeader);
            message: TR2.lookup(TrId.BackupModalDataDetectedContentThisPrime);
            cancel-text: TR2.lookup(TrId.CommonButtonCancel);
            ok-text: TR2.lookup(TrId.CommonButtonConfirm);
            show-cancel: true;
            on-ok => {
                KeycardBackupGlobal.overwrite-keycard(true);
                KeycardBackupGlobal.clear-error();
            }
            on-cancel => {
                KeycardBackupGlobal.overwrite-keycard(false);
                KeycardBackupGlobal.clear-error();
            }
        }
    }

    if KeycardBackupGlobal.fatal-error: Container {
        ErrorDialog {
            title: TR2.lookup(TrId.BackupModalErrorHeader);
            message: TR2.lookup(TrId.BackupModalErrorContent);
            ok-text: TR2.lookup(TrId.CommonButtonRetry);
            on-ok => {
                KeycardBackupGlobal.clear-error();
                root.on-fatal-error()
            }
        }
    }
}
