## SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
## SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "worker-test-disposable"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.14"
log-server = { workspace = true }
rkyv = { workspace = true }
server = { workspace = true }
