// SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { IconButton, SearchInput, TextSm, BasePage, HeadingMd } from "@ui/widgets.slint";
import { Importance, Images, Size, Palette, CurrentTheme } from "@ui/theme.slint";
import { TR2, TrId } from "../gen/tr.slint";

import { BrowserGlobal, SortMode, SortDirection } from "./global.slint";
import { FilePopupMenu, SelectModePopupMenu, SortPopupMenu } from "./popup.slint";
import { LocationSwitcher } from "../location-switcher.slint";
import { ActiveModal, ModalGlobal} from "../modal/global.slint";
import { CopyMoveModal } from "../modal/copy-move.slint";
import { CreateFolderModal } from "../modal/create-folder.slint";
import { DeleteModal } from "../modal/delete.slint";
import { FormatModal } from "../modal/format.slint";
import { RenameModal } from "../modal/rename.slint";
import { FileList, FileListLoading, FileListType } from "../file-list.slint";

export { Images, CurrentTheme }

component BrowserBody inherits Rectangle {
    padding: Size.sz4;

    FileList {
        padding-left: Size.sz6;
        padding-right: Size.sz6;
        file-list: BrowserGlobal.file-lists[BrowserGlobal.location-idx];
        is-select-mode: BrowserGlobal.is-select-mode;
        are-folders-allowed: BrowserGlobal.is-folders-allowed;
        long-press-enabled: true;
        format-allowed: true;

        entry-pressed(name, is-folder) => {
            BrowserGlobal.entry-pressed(name, is-folder);
        }
        entry-long-pressed(name, is-folder) => {
            BrowserGlobal.entry-long-pressed(name, is-folder);
        }
        format-clicked() => {
            BrowserGlobal.format-clicked();
        }
        format-ok-acknowledged() => {
            BrowserGlobal.format-ok-acknowledged();
        }

        header := Rectangle {
            vertical-stretch: 0;

            HorizontalLayout {
                alignment: start;
                VerticalLayout {
                    alignment: center;
                    IconButton {
                        icon: "chevron-left";
                        importance: Importance.tertiary;
                        icon-color: Palette.content-primary;
                        visible: self.enabled;
                        enabled: BrowserGlobal.current-path != "" && !BrowserGlobal.is-select-mode;
                        clicked => {
                            BrowserGlobal.back();
                        }
                    }
                }
            }

            HorizontalLayout {
                alignment: end;
                VerticalLayout {
                    alignment: center;
                    IconButton {
                        icon: "ellipsis";
                        importance: Importance.tertiary;
                        touch-factor: 1.3;
                        clicked => {
                            BrowserGlobal.is-file-menu-open = !BrowserGlobal.is-file-menu-open;
                        }
                    }
                }
            }
        }

        if (BrowserGlobal.is-search-mode): HorizontalLayout {
            vertical-stretch: 0;
            spacing: Size.sz4;

            SearchInput {
                placeholder: TR2.lookup(TrId.CommonFillerTextSearch);
                text: BrowserGlobal.search-query;

                edited(query) => {
                    BrowserGlobal.search-query = query;
                    BrowserGlobal.reload-files();
                }
            }

            IconButton {
                size: Size.sz14;
                icon: BrowserGlobal.sort-direction == SortDirection.Ascending ? "sort-ascending" : "sort-descending";
                importance: BrowserGlobal.sort-mode == SortMode.Alphabetical && BrowserGlobal.sort-direction == SortDirection.Descending ? Importance.secondary : Importance.primary;
                touch-factor: 1.3;
                clicked => {
                    BrowserGlobal.is-sort-menu-open = !BrowserGlobal.is-sort-menu-open;
                }
            }
        }
    }

    Rectangle {
        TouchArea {
            enabled: locations.menu-open;
            clicked => {
                locations.menu-open = false;
            }
        }

        locations := LocationSwitcher {
            x: header.absolute-position.x - root.absolute-position.x + (header.width - self.width) / 2;
            y: header.absolute-position.y - root.absolute-position.y + (header.height - self.height) / 2;

            locations: BrowserGlobal.allowed-locations;
            selected_index: BrowserGlobal.location-idx;
            breadcrumbs: BrowserGlobal.build-breadcrumbs(BrowserGlobal.location-idx, BrowserGlobal.current-path);
            location-changed(index) => {
                BrowserGlobal.location-changed(index);
            }
            breadcrumb-selected(name, index) => {
                BrowserGlobal.breadcrumb-selected(name, index);
            }
        }
    }
}

export component FileBrowser inherits Rectangle {
    Image {
        source: Images.common(CurrentTheme.is-dark ? "images/background-dark" : "images/background");
    }

    BasePage {
        BrowserBody { }
    }

    if BrowserGlobal.is-file-menu-open: Rectangle {
        background: Palette.overlay;
        if BrowserGlobal.is-select-mode: SelectModePopupMenu {
            x: parent.width - self.width - Size.sz4;
            y: 80px;
            z: 100;
        }
        if !BrowserGlobal.is-select-mode: FilePopupMenu {
            x: parent.width - self.width - Size.sz4;
            y: 80px;
            z: 100;
        }

        TouchArea {
            clicked => {
                BrowserGlobal.is-file-menu-open = false;
            }
        }
    }

    if BrowserGlobal.is-sort-menu-open: Rectangle {
        background: Palette.overlay;
        SortPopupMenu {
            x: parent.width - self.width - Size.sz4;
            y: 250px;
            z: 100;
        }

        TouchArea {
            clicked => {
                BrowserGlobal.is-sort-menu-open = false;
            }
        }
    }

    property <ActiveModal> active-modal: ModalGlobal.active-modal;

    if active-modal == ActiveModal.Delete: DeleteModal { }
    if active-modal == ActiveModal.Rename: RenameModal { }
    if active-modal == ActiveModal.CreateFolder: CreateFolderModal { }
    if active-modal == ActiveModal.CopyMove: CopyMoveModal { }
    if active-modal == ActiveModal.Format: FormatModal {
        is-airlock: BrowserGlobal.file-lists[BrowserGlobal.location-idx].is-airlock;
    }
}
