// SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { SegmentModel } from "@ui/widgets/segmented-selector.slint";
import { BreadCrumb } from "../location-switcher.slint";
import { FileListData, FileEntryModel } from "../file-list.slint";

export enum AirlockMode {
    Disabled,
    ReadOnly,
    ReadWrite,
}

export enum SortMode {
    Alphabetical,
    FileSize,
    ModificationDate,
}

export enum SortDirection {
    Ascending,
    Descending,
}

export global BrowserGlobal {
    // UI Mode/Status
    in property <bool> is-folders-allowed: true;
    in property <bool> is-search-mode: false;
    in property <string> search-query: "";
    in property <bool> is-select-mode: false;
    in property <bool> show-hidden-files: false;

    in property <int> location-idx: 0;
    in property <string> current-path: "";

    in property <[SegmentModel]> allowed-locations: [];
    in property <[FileListData]> file-lists: [{ }, { }, { }];

    pure callback build-breadcrumbs(int, string) -> [BreadCrumb];

    in property <AirlockMode> airlock-mode: ReadWrite;

    in property <bool> is-file-menu-open: false;
    in property <bool> show-quick-tip: true;
    in property <bool> is-sort-menu-open: false;

    in property <SortMode> sort-mode: SortMode.Alphabetical;
    in property <SortDirection> sort-direction: SortDirection.Descending;

    callback location-changed(int);
    callback breadcrumb-selected(string, int);
    callback airlock-mode-changed(AirlockMode);
    callback reload-files();
    callback entry-pressed(string, bool);
    callback entry-long-pressed(string, bool);
    callback select-mode-toggled(bool);
    callback hidden-files-toggled(bool);
    callback quick-tip-dismissed();
    callback menu-done();
    callback menu-copy();
    callback menu-move();
    callback menu-rename();
    callback menu-create-folder();
    callback menu-delete();
    callback back();

    callback format-clicked();
    callback format-ok-acknowledged();

    out property <FileListData> active-list: BrowserGlobal.file-lists[BrowserGlobal.location-idx];
    out property <int> selected-count: files-selected-count(active-list.files);

    pure callback files-selected-count(model: [FileEntryModel]) -> int;
}
