[package]
authors = ["Sean Cross <sean@xobs.io>"]
description = "Log server API"
edition = "2018"
name = "xous-api-log"
version = "0.1.28"
license = "MIT OR Apache-2.0"
repository = "https://github.com/betrusted-io/xous-core/"
homepage = "https://betrusted.io/xous-book/"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = { path = "../../xous-rs" }
xous-ipc = { path = "../../ipc" }
log = "0.4.14"
num-derive = "0.4.2"
num-traits = { version = "0.2.18", default-features = false }
xous-api-ticktimer = { path = "../ticktimer" }
xous-api-names = { path = "../names" }

[features]
no_std = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(keyos)'] }
