manifestVersion = "0"
appId = "0xe19f16fcd9610bca7d026b4673f1cb06"
memory = []
syscall = ["SetThreadPriority"]
extends = "../../api/backup"

[appName]
en = "Magic Backup Server"

[servers."os/backup"]
BackupWorkerEvent = { id = 100, type = "archive" }
PeriodicBackup = { id = 101, type = "scalar" }

[permissions]
template = ["fs-generic", "crypto-aes"]
"os/fs" = [
    "GetEncryptedRootReadAccess",
    "GetEncryptedRootWriteAccess",
    "GetSystemReadAccess",
    "GetSystemWriteAccess",
    "GetUserReadAccess",
    "GetUserWriteAccess",
    "GetUsbReadAccess",
    "GetUsbWriteAccess",
    "GetAirlockReadAccess",
    "GetAirlockWriteAccess",
    "SetMtime",
]
"os/quantum-link" = [
    "EnvoyMagicBackupEnabled",
    "SendMagicBackupEvent",
    "SendRestoreMagicBackupResult",
    "SubscribeRestoreMagicBackup",
    "AwaitCreateMagicBackupResult",
    "SubscribeConnectionStatus",
]
"os/crypto" = ["Hmac"]
"os/security" = [
    "GetAppSeed",
    "GetSeedFingerprint",
]
"os/settings" = [
    "SubscribeMagicBackupEnabled",
    "SubscribeOnboardingStatus",
    "GetDeviceName",
    "SetDeviceName",
]
