manifestVersion = "0"
appId = "0x73696d756c61746f7200000000000000"

[appName]
en = "Hosted Mode Simulator"

[permissions]
"os/gui-server" = [
    "CaptureScreen",
    "GetDeviceFrame",
    "SetScaleFactor",
    "Shutdown",
]
"os/settings" = [
    "GetSystemTheme",
    "SetSystemTheme",
    "SubscribeSystemTheme",
]
