// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { AppHeader, BasePage, ContentSection, HeadingMd, HLine, Icon, IconButton, ItemTextPreview, MenuActionItem, MenuItemLayout, MenuSection, MenuSectionLayout, NavHeader, OverlayMenu, PageBody, PopupMenuItem, QrCodeCard, Qrcode, ScrollBody, TextSm, TitledInput, ButtonSection, Button, ConfirmationModal } from "@ui/widgets.slint";
import { TR2, TrId } from "../../gen/tr.slint";
import { Utils } from "@ui/utils.slint";
import { Palette, Size, Importance } from "@ui/theme.slint";
import { DarkPalette } from "@ui/palettes/dark-palette.slint";

import { Navigate } from "../../gen/navigate.slint";
import { AccountProps } from "./props.slint";
import { Callbacks, AccountView, SingleSigView, MultiSigView, Network } from "../../callbacks.slint";
import { ViewMultiSig } from "../../widgets/multisig.slint";
import { CreateAccount } from "../../create-account.slint";
import { SignMessage } from "../../sign-message.slint";

component AccountButtons inherits ButtonSection {
    in property <string> account-id;
    in property <bool> archived;
    in property <bool> is-multisig;

    callback archive-clicked();
    callback delete-clicked();

    if !archived: Button {
        label: TR2.lookup(TrId.DetailsSinglesigArchiveCode);
        icon: "archive";
        importance: Importance.secondary;

        clicked => {
            root.archive-clicked();
        }
    }

    if archived: Button {
        label: TR2.lookup(TrId.ArchivedAccountDeleteAccount);
        importance: Importance.negative;

        clicked => {
            root.delete-clicked();
        }
    }

    if archived: Button {
        label: TR2.lookup(TrId.ArchivedAccountRestoreAccount);
        icon: "export";
        importance: Importance.primary;

        clicked => {
            Callbacks.update-account-archived(account-id, false);
            Navigate.backward();
        }
    }
}

component ArchiveModal inherits ConfirmationModal {
    icon: "info";
    title: TR2.lookup(TrId.ArchiveAccountModalHeader);
    text: TR2.lookup(TrId.ArchiveAccountModalContent);
    confirm-button-label: TR2.lookup(TrId.CommonButtonConfirm);
    cancel-button-label: TR2.lookup(TrId.CommonButtonCancel);
}

component DeleteModal inherits ConfirmationModal {
    in property <string> account-name;

    icon: "alert";
    icon-color: Palette.content-notice;
    title: TR2.lookup(TrId.DeleteAccountModalHeader);
    text: TR2.format(TrId.DeleteAccountModalSubheader, [
        account-name,
    ]);
    confirm-button-label: TR2.lookup(TrId.CommonButtonConfirm);
    cancel-button-label: TR2.lookup(TrId.CommonButtonCancel);
}

component SingleSigViewPage inherits BasePage {
    in property <string> name;
    in property <string> id;
    in property <bool> archived;
    in property <SingleSigView> account;
    in property <Network> network;

    property <bool> menu-open: false;
    property <bool> archive-modal-open: false;
    property <bool> delete-modal-open: false;
    property <bool> label-error: false;

    VerticalLayout {
        NavHeader {
            title: TR2.lookup(TrId.DetailsSinglesigTitle);
            clicked => {
                Navigate.backward();
            }

            right-icon: archived ? "" : "ellipsis";
            right-clicked => {
                menu-open = ! menu-open;
            }
        }

        PageBody {
            ContentSection {
                TitledInput {
                    title: TR2.lookup(TrId.DetailsSinglesigLabel);
                    text: name;
                    show-clear-btn: false;
                    caps-mode: sentences;
                    enabled: !archived;
                    filter-special-characters: true;
                    special-chars-removed-label: TR2.lookup(TrId.CommonCreateAccountsanitizedSpecialCharsRemoved);

                    edited(text) => {
                        if text != name {
                            self.message = CreateAccount.validate-new-label(text);
                            self.has-notice = self.message != "";
                            label-error = self.has-notice;
                        } else {
                            label-error = false;
                        }
                    }

                    accepted(text) => {
                        if !label-error {
                            Callbacks.update-account-name(id, text);
                        }
                    }
                }

                MenuSection {
                    title: TR2.lookup(TrId.DetailsSinglesigDetails);
                    MenuSectionLayout {
                        MenuItemLayout {
                            first: true;
                            label: TR2.lookup(TrId.DetailsSinglesigAccountNumber);
                            ItemTextPreview {
                                text: account.account-number;
                            }
                        }

                        HLine { }

                        MenuItemLayout {
                            last: true;
                            label: TR2.lookup(TrId.DetailsSinglesigFingerprint);
                            ItemTextPreview {
                                text: account.fingerprint;
                            }
                        }
                    }
                }
            }

            AccountButtons {
                account-id: id;
                archived: archived;
                is-multisig: false;

                archive-clicked => {
                    archive-modal-open = true;
                }

                // TODO: handle delete
                delete-clicked => {
                    delete-modal-open = true;
                }
            }
        }
    }

    if menu-open: OverlayMenu {
        PopupMenuItem {
            label: TR2.lookup(TrId.DetailsSinglesigMenuSignMessage);
            icon: "envelope";
            first: true;
            clicked => {
                SignMessage.start-sign-message(id);
            }
        }

        PopupMenuItem {
            label: TR2.lookup(TrId.DetailsSinglesigMenuArchiveAccount);
            icon: "archive";
            last: true;
            clicked => {
                menu-open = false;
                archive-modal-open = true;
            }
        }

        touched-off => {
            menu-open = false;
        }
    }

    if archive-modal-open: ArchiveModal {
        cancel-clicked => {
            archive-modal-open = false;
        }

        confirm-clicked => {
            Callbacks.update-account-archived(id, true);
            archive-modal-open = false;
            Navigate.backward();
        }
    }

    if delete-modal-open: DeleteModal {
        account-name: name;

        cancel-clicked => {
            delete-modal-open = false;
        }

        confirm-clicked => {
            Callbacks.delete-account(id);
            delete-modal-open = false;
            Navigate.backward();
        }
    }
}

export component MultiSigViewPage inherits BasePage {
    in property <string> name;
    in property <string> id;
    in property <bool> archived;
    in property <MultiSigView> account;

    property <bool> menu-open: false;
    property <bool> archive-modal-open: false;
    property <bool> delete-modal-open: false;
    property <bool> label-error: false;

    VerticalLayout {
        NavHeader {
            title: TR2.lookup(TrId.DetailsMultisigTitle);
            clicked => {
                Navigate.backward();
            }
            right-icon: "ellipsis";
            right-clicked => {
                menu-open = ! menu-open;
            }
        }

        ScrollBody {
            VerticalLayout {
                spacing: Size.sz10;
                alignment: space-between;

                ViewMultiSig {
                    multisig: account;

                    TitledInput {
                        title: TR2.lookup(TrId.DetailsMultisigLabel);
                        text: name;
                        show-clear-btn: false;
                        caps-mode: sentences;
                        enabled: !archived;
                        filter-special-characters: true;
                        special-chars-removed-label: TR2.lookup(TrId.CommonCreateAccountsanitizedSpecialCharsRemoved);

                        edited(text) => {
                            if text != name {
                                self.message = CreateAccount.validate-new-label(text);
                                self.has-notice = self.message != "";
                                label-error = self.has-notice;
                            } else {
                                label-error = false;
                            }
                        }

                        accepted(text) => {
                            if !label-error {
                                Callbacks.update-account-name(id, text);
                            }
                        }
                    }
                }

                AccountButtons {
                    account-id: id;
                    archived: archived;
                    is-multisig: true;

                    archive-clicked => {
                        archive-modal-open = true;
                    }

                    delete-clicked => {
                        delete-modal-open = true;
                    }
                }
            }
        }
    }

    if menu-open: OverlayMenu {
        PopupMenuItem {
            label: TR2.lookup(TrId.DetailsMultisigMenuExportConfig);
            icon: "export";
            first: true;
            clicked => {
                Navigate.scan-connect({ account-id: id }, { });
            }
        }

        PopupMenuItem {
            label: TR2.lookup(TrId.DetailsSinglesigMenuArchiveAccount);
            icon: "archive";
            last: true;
            clicked => {
                menu-open = false;
                archive-modal-open = true;
            }
        }

        touched-off => {
            menu-open = false;
        }
    }

    if archive-modal-open: ArchiveModal {
        cancel-clicked => {
            archive-modal-open = false;
        }

        confirm-clicked => {
            Callbacks.update-account-archived(id, true);
            archive-modal-open = false;
            Navigate.backward();
        }
    }

    if delete-modal-open: DeleteModal {
        account-name: name;

        cancel-clicked => {
            delete-modal-open = false;
        }

        confirm-clicked => {
            Callbacks.delete-account(id);
            delete-modal-open = false;
            Navigate.backward();
        }
    }
}

export component AccountPage inherits Rectangle {
    in property <AccountProps> props;

    property <AccountView> account: Callbacks.account-details(props.account-id);
    if account.is-multisig: MultiSigViewPage {
        name: account.name;
        id: account.id;
        account: account.multi;
        archived: account.archived;
    }

    if !account.is-multisig: SingleSigViewPage {
        name: account.name;
        id: account.id;
        account: account.single;
        network: account.network;
        archived: account.archived;
    }
}
