# SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "gui-app-system-actions"
version = "0.1.0"
edition = "2021"

[dependencies]
fs = { workspace = true }
getrandom = { workspace = true }
keyos = { path = "../../keyos" }
log = "0.4.14"
log-server = { package = "xous-api-log", path = "../../xous/api/log" }
server = { path = "../../server" }
slint-keyos-platform = { path = "../../slint-keyos-platform/runtime" }

[build-dependencies]
slint-keyos-platform-build = { path = "../../slint-keyos-platform/build", default-features = false }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(keyos)'] }
