manifestVersion = "0"
appId = "0x6775692d6170702d73797374656d2d61"

[appName]
en = "System Actions"

[permissions]
template = ["gui-app"]
"os/gui-server" = ["Shutdown"]
"os/settings" = [
    "GetTouchOffset",
    "SetTouchOffset",
    "SetDebugTouch",
]
