// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

use std::{fs::File, io::Write, path::PathBuf};

const DEFAULT_MANIFESTS: &[u8] = b"// THIS IS A GENERATED FILE, DO NOT EDIT.
// Generated by build.rs, setting empty list.
// The actual list should be generated by xtask,
// based on the selected system services.

pub const SYSTEM_MANIFESTS: &[&str] = &[];
";

fn main() {
    let project_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let system_manifests_path = PathBuf::from(project_dir).join("src/system_manifests.rs");
    if !system_manifests_path.exists() {
        let mut f = File::create(system_manifests_path).unwrap();
        f.write_all(DEFAULT_MANIFESTS).unwrap();
    }
}
