manifestVersion = "0"
appId = "0xab4db82af4fb26eaa349e39b6e128698"

[appName]
en = "settings test client"

[permissions]
"os/settings" = [
    "SetSystemTheme",
    "GetSystemTheme",
    "SubscribeSystemTheme",
    "SetDeviceName",
    "GetDeviceName",
    "SubscribeDeviceName",
]
