// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

export enum SeedViewType {
    bitcoin-12,
    bitcoin-24,
    password,
    nostr-key,
    nostr-key-import,
    password-generated,
    bitcoin-import-12,
    bitcoin-import-24,
}

// This handles all bitcoin seeds and nostr keys
export struct IndexedSeedView {
    index: string,  // Uses a string to represent u32, since slint ints are i32
}

export struct PasswordView {
    account: string,
    password: string,
}

export struct ImportedSeedInfo {
    entropy: string,
    fingerprint: string,
}

export struct SeedView {
    label: string,
    color: int,
    seed-type: SeedViewType,
    indexed-seed: IndexedSeedView,
    password: PasswordView,
    index: int,
}
