manifestVersion = "0"
appId = "0x46696c652042726f7773657200000000"

[appName]
en = "Files"

[permissions]
template = ["gui-app", "navigable", "fs-generic"]
"os/fs" = [
    "GetUsbReadAccess",
    "GetUsbWriteAccess",
    "GetUserReadAccess",
    "GetUserWriteAccess",
    "GetAirlockReadAccess",
    "GetAirlockWriteAccess",
    "FormatUsb",
    "FormatAirlock",
    "MountAirlock",
]
"os/settings" = ["SubscribeAirlockMode", "SetAirlockMode"]
