manifestVersion = "0"
appId = "0x6f732f6E666300000000000000000000"
syscall = ["SetThreadPriority"]
extends = "../../api/nfc"

[appName]
en = "NFC Server"

[permissions]
template = ["gpio"]
"os/fido" = ["U2fProcessApdu", "CtapProcessCbor"]
"os/gpio" = ["SetIrq"]
"os/spi" = ["ClaimPeripheral", "SpiXfer", "St25r95ReadData"]
"os/settings" = ["SubscribeNfcEnabled"]
