// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

//! App switcher gesture logic

use gui_server_api::{
    consts::{
        SCREEN_HEIGHT, SCREEN_WIDTH, VIRT_BUTTON_PHYS_HEIGHT, VIRT_BUTTON_PHYS_ORIGIN_X,
        VIRT_BUTTON_PHYS_ORIGIN_Y, VIRT_BUTTON_PHYS_WIDTH,
    },
    touch::{Touch, TouchKind},
    InputMessage,
};

use crate::{touch::TouchGestureOrigin, Gui};

const VIRT_BUTTON_TO_SCREEN_GAP: usize = VIRT_BUTTON_PHYS_ORIGIN_Y - SCREEN_HEIGHT;
const UP_GESTURE_APP_SWITCHER_MIN_DISTANCE: f32 = 8.0;
const UP_GESTURE_APP_SWITCHER_MAX_DISTANCE: f32 = 300.0;

/// The distance threshold after which the app switcher gesture is considered completed
/// and the app switcher is entered upon release.
const UP_GESTURE_APP_SWITCHER_DISTANCE_THRESHOLD: f32 = UP_GESTURE_APP_SWITCHER_MAX_DISTANCE * 0.68;

const UP_GESTURE_TIMEOUT_TICKS: usize = 15;

#[derive(Default)]
pub(crate) struct SwitcherGestureState {
    pub started: bool,
    pub virt_button_initial_pos: Option<Touch>,
    pub last_gesture_was_virtual_button_up: bool,

    /// When timeout is set, it will decrement at VSYNC speed.
    /// When it reaches 0, the gesture is aborted.
    pub timeout_ticks: Option<usize>,
}

impl SwitcherGestureState {
    pub(crate) fn reset(&mut self) {
        self.started = false;
        self.virt_button_initial_pos = None;
        self.last_gesture_was_virtual_button_up = false;
        self.timeout_ticks = None;
    }
}

pub(crate) fn process_touch(gui: &mut Gui, touch: Touch) {
    // Cancel out the touch offset for the gesture handling
    let touch = touch.with_offset(0, -gui.touch_state.offset);
    let is_within_home_button = touch.is_within_area(
        VIRT_BUTTON_PHYS_ORIGIN_X,
        VIRT_BUTTON_PHYS_ORIGIN_Y,
        VIRT_BUTTON_PHYS_WIDTH,
        VIRT_BUTTON_PHYS_HEIGHT,
    );

    let Some(origin) = gui.touch_state.switcher_gesture_state.virt_button_initial_pos else {
        log::warn!("No gesture origin");
        return;
    };

    let (_dx, dy) = touch.diff(&origin);
    let gesture_up = dy < 0;
    let distance_y = dy.abs() as f32;

    match touch.kind {
        TouchKind::Drag => {
            // Don't process touch below the starting point of the gesture
            if !gesture_up {
                return;
            }

            // Abort timeout, if any
            gui.touch_state.switcher_gesture_state.timeout_ticks.take();

            // If the switcher gesture hasn't started yet, check the traveled distance
            // of the upwards drag to initiate it
            if !gui.touch_state.switcher_gesture_state.started {
                if distance_y < UP_GESTURE_APP_SWITCHER_MIN_DISTANCE {
                    return;
                }

                gui.haptics_click();
                gui.rgb_led.virt_button_press_animation();
                gui.touch_state.switcher_gesture_state.started = true;
                gui.touch_state.origin = TouchGestureOrigin::AppSwitcherGesture;

                // After this, the animation is controlled by the user dragging up or down
                gui.switch_to_app_switcher();
                if let Some(switched_from) = gui.background_pid() {
                    gui.notify_switcher_update_app_fb(switched_from);
                }
            } else {
                let distance_y = if is_within_home_button {
                    distance_y
                } else {
                    // Subtract the gap between the screen and the home button where we can't receive touches
                    (distance_y - VIRT_BUTTON_TO_SCREEN_GAP as f32)
                        .clamp(0., UP_GESTURE_APP_SWITCHER_MAX_DISTANCE)
                };
                let progress = distance_y / UP_GESTURE_APP_SWITCHER_MAX_DISTANCE * 100.0;
                let progress = progress.clamp(5.0, 99.0); // 100% progress can only be reached on release
                gui.set_switching_animation_progress(Some(progress as usize));
            }
        }
        TouchKind::Release => {
            // TODO: if reached sufficient velocity, finalize the switcher animation

            // Ignore release generated by crossing the border between the home button and the screen
            if touch.is_within_area(0, SCREEN_HEIGHT - 10, SCREEN_WIDTH, 10)
                || touch.is_within_area(0, VIRT_BUTTON_PHYS_ORIGIN_Y - 16, SCREEN_WIDTH, 32)
            {
                gui.touch_state.switcher_gesture_state.timeout_ticks = Some(UP_GESTURE_TIMEOUT_TICKS);
                return;
            }

            gui.rgb_led.virt_button_release_animation();
            gui.touch_state.switcher_gesture_state.reset();
            gui.touch_state.origin = TouchGestureOrigin::None;

            if distance_y > UP_GESTURE_APP_SWITCHER_DISTANCE_THRESHOLD {
                // Complete the switcher animation and enter it
                gui.set_switching_animation_progress(None);
            } else {
                // Abort the switcher, go back to the app
                gui.abort_switching_animation();
            }
        }
        TouchKind::Press => (), // The gesture is performed until release and no press is expected
    }
}

impl Gui {
    pub(crate) fn switcher_timeout_tick(&mut self) {
        let Some(ticks) = &mut self.touch_state.switcher_gesture_state.timeout_ticks else {
            return;
        };

        *ticks = ticks.saturating_sub(1);

        if *ticks == 0 && self.touch_state.switcher_gesture_state.started {
            self.rgb_led.virt_button_release_animation();
            self.touch_state.switcher_gesture_state.reset();
            self.touch_state.origin = TouchGestureOrigin::None;
            self.abort_switching_animation();
        }
    }

    fn send_switcher_message(
        &self,
        pid: xous::PID,
        create_message: impl FnOnce(xous::PID) -> Option<xous::Message>,
    ) {
        let Some(switcher_pid) = self.app_registry.switcher_app_pid() else { return };
        let Some(switcher_window) = self.windows.get(&switcher_pid) else { return };
        // Don't update the switcher on the apps that aren't supposed to be shown there
        if self.app_registry.is_essential_app(pid) {
            return;
        }
        let Some(msg) = create_message(pid) else {
            return;
        };
        if let Err(e) = xous::send_message(switcher_window.input_cid, msg) {
            log::error!("Failed to notify switcher: {e:?}");
        }
    }

    pub(crate) fn notify_switcher_app_started(&self, pid: xous::PID, name: &str) {
        self.send_switcher_message(pid, |pid| {
            let Ok(mut name_page) = xous::map_memory(None, None, 0x1000, xous::MemoryFlags::W) else {
                log::error!("Couldn't allocate switcher app started message");
                return None;
            };
            let name_bytes = name.as_bytes();
            name_page.as_slice_mut()[..name_bytes.len()].copy_from_slice(name_bytes);
            Some(xous::Message::new_move(
                InputMessage::Custom1 as usize,
                name_page,
                Some(pid.into()),
                xous::MemorySize::new(name_bytes.len()),
            ))
        });
    }

    pub(crate) fn notify_switcher_app_activated(&self, pid: xous::PID) {
        self.send_switcher_message(pid, |pid| {
            Some(xous::Message::new_scalar(InputMessage::Custom2 as usize, pid.get() as usize, 0, 0, 0))
        });
    }

    pub(crate) fn notify_switcher_update_app_fb(&self, pid: xous::PID) {
        // 4 bytes per pixel, but half width and half height.
        const BUFFER_SIZE: usize = SCREEN_WIDTH * SCREEN_HEIGHT;
        self.send_switcher_message(pid, |pid| {
            let app_window = self.windows.get(&pid)?;
            let Ok(mut fb) =
                xous::map_memory(None, None, BUFFER_SIZE.next_multiple_of(0x1000), xous::MemoryFlags::W)
            else {
                log::error!("Couldn't allocate switcher app fb message");
                return None;
            };
            let Some(display_buffer) = app_window.buffers.most_recent_buffer() else {
                log::error!("App window doesn't have buffers for switcher");
                return None;
            };

            // Resize to 0.5x in both directions
            for y in 0..SCREEN_HEIGHT / 2 {
                for x in 0..SCREEN_WIDTH / 2 {
                    let pixel: u32 = display_buffer.as_slice()[y * 2 * SCREEN_WIDTH + x * 2];
                    // Swap back R and B from hw representation
                    #[cfg(keyos)]
                    let pixel =
                        (pixel & 0xff00ff00) | ((pixel & 0xff0000) >> 16) | ((pixel & 0x0000ff) << 16);
                    fb.as_slice_mut()[y * (SCREEN_WIDTH / 2) + x] = pixel;
                }
            }

            Some(xous::Message::new_move(InputMessage::Custom3 as usize, fb, Some(pid.into()), None))
        });
    }

    pub(crate) fn notify_switcher_app_closed(&self, pid: xous::PID) {
        self.send_switcher_message(pid, |pid| {
            Some(xous::Message::new_scalar(InputMessage::Custom4 as usize, pid.get() as usize, 0, 0, 0))
        });
    }
}
