// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Callbacks as CB } from "../../../callbacks.slint";
import { BasePage, AppHeader, IconButton, SeedWords, ButtonSection, Button, QrPages } from "@ui/widgets.slint";
import { Importance, Size, Utils, Palette } from "@ui/theme.slint";
import { SeedView, SeedViewType } from "../../../types.slint";
import { DetailsProps } from "../props.slint";
import { ViewProps } from "./props.slint";
import { Navigate } from "../../../gen/navigate.slint";
import { TR2, TrId } from "../../../gen/tr.slint";

export component ViewPage inherits BasePage {
    in property <DetailsProps> details-props;
    in property <ViewProps> props;

    property <SeedView> seed;
    property <bool> qr-view: false;
    property <[string]> words;
    property <image> standard-qr;
    property <image> compact-qr;
    property <string> npub;
    property <string> nsec;

    init => {
        seed = CB.get-seed-details(details-props.index);
        words = CB.get-words(seed.index);
        standard-qr = CB.get-standard-seed-qr(seed.index);
        compact-qr = CB.get-compact-seed-qr(seed.index);
        npub = CB.get-npub(seed.index);
        nsec = CB.get-nsec(seed.index);
    }

    pure function get-view-title(seed-type: SeedViewType) -> string {
        if (CB.is-bitcoin(seed-type)) {
            return TR2.lookup(TrId.ViewSeedWordsTitle);
        } else if (CB.is-nostr(seed-type)) {
            return TR2.lookup(TrId.ViewNostrKeyTitle);
        }
        return TR2.lookup(TrId.ViewSeedWordsTitle);
        ;
    }

    VerticalLayout {
        AppHeader {
            title: get-view-title(seed.seed-type);
            side-padding: Size.sz8;

            IconButton {
                icon: "chevron-left";
                size: Size.sz8;
                importance: Importance.normal;
                clicked => {
                    Navigate.backward();
                }
            }

            if !CB.is-nostr(seed.seed-type): IconButton {
                icon: qr-view ? "list" : "scan-qr";
                size: Size.sz8;
                importance: Importance.normal;
                clicked => {
                    qr-view = !qr-view;
                }
            }
        }

        VerticalLayout {
            padding-top: (CB.is-nostr(seed.seed-type) || qr-view) ? Size.sz2 : Size.sz16;
            padding-bottom: Size.sz4;

            if (!CB.is-nostr(seed.seed-type) && !qr-view): SeedWords {
                words: words;
            }

            if (!CB.is-nostr(seed.seed-type) && qr-view): QrPages {
                model: [
                    {
                        code: standard-qr,
                        header: TR2.lookup(TrId.ViewSeedWordsStandardSeedQr),
                    },
                    {
                        code: compact-qr,
                        header: TR2.lookup(TrId.ViewSeedWordsCompactSeedQr),
                    },
                ];
            }

            if CB.is-nostr(seed.seed-type): QrPages {
                model: [
                    {
                        code: Utils.qrcode(npub, Palette.black, Palette.white),
                        header: TR2.lookup(TrId.ArchivedItemNostrKeyPublicKey),
                        footer: npub,
                        footer-is-address: true,
                    },
                    {
                        code: Utils.qrcode(nsec, Palette.black, Palette.white),
                        header: TR2.lookup(TrId.ArchivedItemNostrKeyPrivateKey),
                        footer: nsec,
                        footer-is-address: true,
                    },
                ];
            }

            ButtonSection {
                padding: Size.sz6;
                padding-left: Size.sz6;
                padding-right: Size.sz6;

                Button {
                    label: TR2.lookup(TrId.CommonButtonDone);

                    clicked => {
                        Navigate.backward();
                    }
                }
            }
        }
    }
}
