// SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Palette, UISize, Size, Images } from "@ui/theme.slint";
import { Navigate } from "../../../gen/navigate.slint";
import { HeadingMd, TextSm, TextMd, Icon, Shield, Button, ButtonSection } from "@ui/widgets.slint";
import { OnboardingBasePage } from "../../../widgets/base-page.slint";
import { OnboardingCallbacks } from "../../../onboarding-callbacks.slint";
import { ShieldSection, ShieldContent, OnboardingShieldPage, OverlayImage } from "../../../widgets/shield-page.slint";
import { TR2, TrId } from "../../../gen/tr.slint";

export component SetPinInfoPage inherits OnboardingShieldPage {
    ShieldSection {
        ShieldContent {
            VerticalLayout {
                spacing: Size.sz10;
                HeadingMd {
                    vertical-stretch: 0;
                    text: TR2.lookup(TrId.SetPinHeader);
                    horizontal-alignment: center;
                }

                TextMd {
                    text: TR2.lookup(TrId.SetPinContent);
                    color: Palette.content-secondary;
                    horizontal-alignment: center;
                }
            }
        }

        ButtonSection {
            Button {
                label: TR2.lookup(TrId.CommonButtonContinue);
                importance: primary;
                clicked => {
                    Navigate.set-pin-set({ });
                }
            }
        }
    }

    OverlayImage {
        image: "images/three-d/pin";
    }
}
