# SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

# do not include in workspace
# try to keep workspace lean
[workspace]

[package]
name = "keyos-log-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
arboard = "3"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.27"
log = "0.4"
ratatui = "0.30"
regex = "1"
textwrap = "0.16"
usb-debug-protocol = { path = "../../os/usb-debug/protocol", features = ["client"] }
