manifestVersion = "0"
appId = "0x6775692d6170702d6578616d706c652e"

[appName]
en = "QR Scanner"

[permissions]
template = ["gui-app", "navigable"]
"os/app-manager" = ["GetQrMatchRules"]
"os/camera" = ["Subscribe", "GetParams", "SetParams"]
"os/gui-server" = ["ShowCamera", "HideCamera"]
"os/haptics" = ["Vibrate"]
"os/settings" = ["SetCameraEnabled", "SubscribeCameraEnabled"]
