manifestVersion = "0"
appId = "0x616363656c65726f6d657465720a0000"
syscall = ["SetThreadPriority"]

[appName]
en = "Accelerometer sensor"

[servers."os/accelerometer"]
AccelerometerSubscribe = { id = 1, type = "scalarEvent" }
AccelerometerPoll = { id = 64, type = "blockingScalar" }

[permissions]
"template" = ["i2c", "gpio"]
