# SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "gui-app-control-center"
version = "0.1.0"
edition = "2021"

[features]
recovery-os = ["slint-keyos-platform/recovery-os"]
default = []

[dependencies]
anyhow = { workspace = true }
backup = { workspace = true }
bt = { workspace = true }
gui-server-api = { workspace = true }
haptics = { workspace = true }
i18n = { version = "0.1.0", path = "../../i18n" }
jiff = { version = "0.2.5", default-features = false, features = ["alloc", "std"] }
log = { workspace = true }
log-server = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
power-manager = { workspace = true }
rkyv = { workspace = true }
security = { workspace = true }
server = { workspace = true }
shared-fut = { workspace = true }
slint-keyos-platform = { path = "../../slint-keyos-platform/runtime" }
xous = { workspace = true }
xous-ipc = { workspace = true }
xous-names = { workspace = true }

[target.'cfg(keyos)'.dependencies]
camera = { workspace = true }
nfc = { workspace = true }
usb = { workspace = true }

[build-dependencies]
slint-keyos-platform-build = { path = "../../slint-keyos-platform/build" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(keyos)'] }
