manifestVersion = "0"
appId = "0x5365637572697479204b657973000000"

[appName]
en = "Keys"

[permissions]
template = ["gui-app", "navigable", "fs-generic"]
"os/fido" = [
    "SubscribeKeyChanges",
    "SubscribePresenceKeepAlive",
    "SubscribeOperationOutcomes",
    "ListSecurityKeys",
    "CreateSecurityKey",
    "EditSecurityKey",
    "SetArchived",
    "SelectSecurityKey",
    "GetSelectedSecurityKey",
]
"os/haptics" = ["Vibrate"]
"os/nfc" = ["IsEnabled"]
"os/settings" = ["GetUsbEnabled"]
