# SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "camera"
version = "0.1.0"
edition = "2021"
description = "Camera API crate"
publish = false

[dependencies]
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
rkyv = { workspace = true }
server = { workspace = true }
xous = { workspace = true }

[target.'cfg(not(keyos))'.dependencies]
rand = "0.8"
shared_memory = { version = "0.12.4", features = ["logging"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(keyos)'] }
