manifestVersion = "0"
[servers."os/settings"]
LookupTimeZone = { id = 5, type = "blockingArchive" }
ListTimeZone = { id = 6, type = "blockingArchive" }
FlushAll = { id = 7, type = "scalar" }
GetPrimeColor = { id = 9, type = "blockingScalar" }
ResetSettings = { id = 10, type = "blockingScalar" }
GetSystemTheme = { id = 20, type = "blockingScalar" }
SetSystemTheme = { id = 21, type = "scalar" }
SubscribeSystemTheme = { id = 22, type = "scalarEvent" }
GetOnboardingStatus = { id = 23, type = "blockingArchive" }
SetOnboardingStatus = { id = 24, type = "archive" }
SubscribeOnboardingStatus = { id = 25, type = "archiveEvent" }
GetScreenBrightness = { id = 26, type = "blockingScalar" }
SetScreenBrightness = { id = 27, type = "scalar" }
SubscribeScreenBrightness = { id = 28, type = "scalarEvent" }
GetLocale = { id = 29, type = "blockingScalar" }
SetLocale = { id = 30, type = "scalar" }
SubscribeLocale = { id = 31, type = "scalarEvent" }
GetDeviceName = { id = 32, type = "blockingArchive" }
SetDeviceName = { id = 33, type = "archive" }
SubscribeDeviceName = { id = 34, type = "archiveEvent" }
GetShowSecurityWords = { id = 35, type = "blockingScalar" }
SetShowSecurityWords = { id = 36, type = "scalar" }
SubscribeShowSecurityWords = { id = 37, type = "scalarEvent" }
GetAutoLock = { id = 38, type = "blockingScalar" }
SetAutoLock = { id = 39, type = "scalar" }
SubscribeAutoLock = { id = 40, type = "scalarEvent" }
GetEnvoyTimeSync = { id = 41, type = "blockingScalar" }
SetEnvoyTimeSync = { id = 42, type = "scalar" }
SubscribeEnvoyTimeSync = { id = 43, type = "scalarEvent" }
GetUseStandardTimeFormat = { id = 44, type = "blockingScalar" }
SetUseStandardTimeFormat = { id = 45, type = "scalar" }
SubscribeUseStandardTimeFormat = { id = 46, type = "scalarEvent" }
GetTimeZone = { id = 47, type = "blockingArchive" }
SetTimeZone = { id = 48, type = "archive" }
SubscribeTimeZone = { id = 49, type = "archiveEvent" }
GetDebugTouch = { id = 50, type = "blockingScalar" }
SetDebugTouch = { id = 51, type = "scalar" }
SubscribeDebugTouch = { id = 52, type = "scalarEvent" }
GetAirlockMode = { id = 53, type = "blockingScalar" }
SetAirlockMode = { id = 54, type = "scalar" }
SubscribeAirlockMode = { id = 55, type = "scalarEvent" }
GetTouchOffset = { id = 56, type = "blockingScalar" }
SetTouchOffset = { id = 57, type = "scalar" }
SubscribeTouchOffset = { id = 58, type = "scalarEvent" }
GetMagicBackupEnabled = { id = 59, type = "blockingScalar" }
SetMagicBackupEnabled = { id = 60, type = "scalar" }
SubscribeMagicBackupEnabled = { id = 61, type = "scalarEvent" }
GetNfcEnabled = { id = 62, type = "blockingScalar" }
SetNfcEnabled = { id = 63, type = "scalar" }
SubscribeNfcEnabled = { id = 64, type = "scalarEvent" }
GetBluetoothEnabled = { id = 65, type = "blockingScalar" }
SetBluetoothEnabled = { id = 66, type = "scalar" }
SubscribeBluetoothEnabled = { id = 67, type = "scalarEvent" }
GetCameraEnabled = { id = 68, type = "blockingScalar" }
SetCameraEnabled = { id = 69, type = "scalar" }
SubscribeCameraEnabled = { id = 70, type = "scalarEvent" }
GetUsbEnabled = { id = 71, type = "blockingScalar" }
SetUsbEnabled = { id = 72, type = "scalar" }
SubscribeUsbEnabled = { id = 73, type = "scalarEvent" }
