manifestVersion = "0"
appId = "0x66732d62656e63686d61726b00000000"

[appName]
en = "fs benchmark"

[permissions]
template = ["fs-generic"]
"os/fs" = [
    "GetUsbReadAccess",
    "GetUsbWriteAccess",
    "GetSystemReadAccess",
    "GetSystemWriteAccess",
    "GetAirlockReadAccess",
    "GetAirlockWriteAccess",
]
"os/security" = ["Login"]
"os/usb" = ["SetEnabled"]
