manifestVersion = "0"
appId = "0x8abc821d427553efab0c6b374d059bda"

[appName]
en = "FIDO Server"

[servers."os/fido"]
GetSelectedSecurityKey = { id = 0, type = "blockingScalar" }
SelectSecurityKey = { id = 1, type = "scalar" }
SubscribeKeyChanges = { id = 2, type = "archiveEvent" }
SubscribePresenceKeepAlive = { id = 3, type = "archiveEvent" }
SubscribeOperationOutcomes = { id = 4, type = "archiveEvent" }
CreateSecurityKey = { id = 5, type = "blockingArchive" }
EditSecurityKey = { id = 6, type = "blockingArchive" }
SetArchived = { id = 7, type = "blockingScalar" }
ListSecurityKeys = { id = 8, type = "blockingArchive" }
U2fProcessApdu = { id = 9, type = "blockingArchive" }
CtapProcessCbor = { id = 10, type = "blockingArchive" }
ResetState = { id = 11, type = "blockingScalar", cfg = "feature = \"test-app\"" }
DisconnectHandlerMessage = { id = 12, type = "scalar" }

[permissions]
template = ["fs-generic", "crypto-sha"]
"os/crypto" = ["Hmac"]
"os/fs" = []
"os/gui-server" = ["NavigateTo"]
"os/security" = ["SignWithFidoKey", "GetAppSeed", "GetFidoPubkey"]
"os/settings" = ["SubscribeOnboardingStatus"]
