manifestVersion = "0"
appId = "0xbf5cdfbfda7e85b5253ff268d32ea957"
syscall = ["CreateProcess", "GetPanicMessage"]
extends = "../../api/app-manager"

[appName]
en = "App Manager"

[servers."os/app-manager"]
ChildCrashed = { id = 5, type = "scalar" }
Disconnected = { id = 6, type = "scalar" }

[permissions]
template = ["fs-generic", "crypto-sha"]
"os/crypto" = ["ShaSetContext", "ShaUpdate", "ShaGetContext", "ShaDrop"]
"os/fs" = ["GetSystemReadAccess"]
"os/nameserver" = ["AddManifest"]
