manifestVersion = "0"
appId = "0x6c6f672d7573622d73657269616c0000"
syscall = ["DebugCommand"]

[appName]
en = "Log over USB serial"

[permissions]
"os/usbdev" = [
    "ReadEndpoint",
    "WriteEndpoint",
    "NumInterfaces",
    "RegisterSetupResponder",
    "RegisterInterface",
    "WaitForConnection",
]
"os/log" = ["ReadLogs"]
