manifestVersion = "0"
appId = "0x7267622d736572766572000000000000"
syscall = ["SetThreadPriority"]
extends = "../../api/rgb-led"

[appName]
en = "RGB LED server"

[permissions]
"template" = ["i2c", "gpio"]
