manifestVersion = "0"
appId = "0x7c9f81f9bcee31425062fb0d8fbf3001"

[appName]
en = "Dev Playground"

[permissions]
template = ["gui-app", "fs-generic"]
"os/haptics" = ["Vibrate"]
"os/bt" = ["TestEcho"]
"os/rgb-server" = ["SetAllTo", "SetTo"]
"os/nfc" = ["SetEnabled"]
"os/keycard" = ["IdentifyKeycard", "FormatKeycard"]
"os/backup" = ["CreateBackup", "RestoreBackup"]
"os/quantum-link" = ["StartRestoreMagicBackup"]
"os/fs" = [
    "GetUsbReadAccess",
    "GetAirlockReadAccess",
    "GetUserReadAccess",
    "GetSystemReadAccess",
    "GetSystemWriteAccess",
]
