# SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "security-server"
version = "0.1.0"
edition = "2021"

[features]
recovery-os = []
default = []
production = []

[dependencies]
bip39 = "2.1"
constant_time_eq = "0.3"
crypto = { workspace = true }
hex = "0.4.3"
log = "0.4"
log-server = { package = "xous-api-log", path = "../../xous/api/log" }
p256 = "0.13.2"
power-manager = { workspace = true }
rand = "0.8"
rkyv = { workspace = true }
security = { workspace = true }
server = { path = "../../server" }
sha2 = "0.10"
xous = { path = "../../xous/xous-rs" }
xous-ipc = { path = "../../xous/ipc" }
xous-names = { package = "xous-api-names", path = "../../xous/api/names" }
zeroize = { version = "1.8.1", default-features = false, features = ["zeroize_derive"] }

[target.'cfg(keyos)'.dependencies]
atsama5d27 = { path = "../../imports/atsama5d27" }
cryptoauthlib = { path = "../../cryptoauthlib" }
dma = { workspace = true }
gpio = { workspace = true }
securam-manager = { path = "../../imports/securam-manager" }

[target.'cfg(not(keyos))'.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(keyos)'] }
