# SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "keycard-server"
version = "0.1.0"
edition = "2021"

[dependencies]
backup-shard = { workspace = true }
crypto = { workspace = true }
keycard = { workspace = true }
log = { workspace = true }
log-server = { workspace = true }
ndef = { workspace = true }
nfc = { workspace = true }
security = { workspace = true }
server = { workspace = true }
xous = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(keyos)'] }
