manifestVersion = "0"
appId = "0xe3b0c44298fc1c149afbf4c8996fb924"
extends = "../../api/keycard"

[appName]
en = "Keycard Server"

[permissions]
template = ["crypto-sha"]
"os/crypto" = ["ShamirSplit", "ShamirRecover"]
"os/security" = [
    "GetDeviceId",
    "GetSeed",
    "GetSeedFingerprint",
    "ComputeSeedFingerprint",
    "KeycardAuthenticityMac",
]
"os/nfc" = ["ReadNdefRawMsg", "WriteNdefRawMsg"]
