// SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Palette, Size } from "@ui/theme.slint";
import { Button, ButtonSection, HeadingMd, NavHeader, TextMd, WrappedIcon, JumboIconPageBody } from "@ui/widgets.slint";
import { TR2, TrId } from "../../../../gen/tr.slint";

import { Navigate } from "../../../../gen/navigate.slint";
import { SeedGlobal,  MasterSeedState, OnboardingCallbacks } from "../../../../onboarding-callbacks.slint";
import { OnboardingBasePage, OnboardingContentSection } from "../../../../widgets/base-page.slint";
import { RestoreSeedLoading, RestoreSuccessContent, RestoreFailed } from "../../../../widgets/restore-seed.slint";


component Success inherits JumboIconPageBody {
    RestoreSuccessContent { }

    ButtonSection {
        Button {
            label: TR2.lookup(TrId.CommonButtonContinue);
            importance: primary;
            clicked => {
                if (SeedGlobal.is-master-key-recovery) {
                    OnboardingCallbacks.finish-onboarding();
                } else {
                    Navigate.restore-magic-backup({ });
                }
            }
        }
    }
}

component SeedQrError inherits VerticalLayout {
    callback retry();

    NavHeader {
        clicked => {
            SeedGlobal.seed-qr-error = false;
            Navigate.backward();
        }
    }

    JumboIconPageBody {
        padding-top: Size.zero;

        OnboardingContentSection {
            HorizontalLayout {
                alignment: center;
                WrappedIcon {
                    outer-icon: "jumbo-circle";
                    inner-icon: "close";
                }
            }

            HeadingMd {
                text: TR2.lookup(TrId.SeedQrErrorHeader);
                horizontal-alignment: center;
            }

            TextMd {
                text: TR2.lookup(TrId.SeedQrErrorContent);
                color: Palette.content-tertiary;
                horizontal-alignment: center;
            }
        }

        ButtonSection {
            Button {
                label: TR2.lookup(TrId.CommonButtonRetry);
                importance: primary;
                clicked => {
                    root.retry();
                }
            }
        }
    }
}

export component RestoreSeedQrPage inherits OnboardingBasePage {
    property <MasterSeedState> state <=> SeedGlobal.master-seed-state;

    if SeedGlobal.seed-qr-error: SeedQrError {
        retry => {
            SeedGlobal.seed-qr-error = false;
            SeedGlobal.restore-from-seed-qr();
        }
    }
    if !SeedGlobal.seed-qr-error && (state == MasterSeedState.SavingToSE || state == MasterSeedState.EncryptingFs): RestoreSeedLoading { }
    if !SeedGlobal.seed-qr-error && state == MasterSeedState.Success: Success { }
    if !SeedGlobal.seed-qr-error && state == MasterSeedState.Failed: RestoreFailed {
        // todo: i18n
        title: "Failed to restore from SeedQR";
        retry => {
            state = MasterSeedState.Idle;
            SeedGlobal.restore-from-seed-qr();
        }
    }
}
