manifestVersion = "0"
[servers."os/power-manager"]
SetPeripheralEnabled = { id = 0, type = "blockingScalar", cfg = "keyos" }
Shutdown = { id = 1, type = "blockingScalar" }
Reboot = { id = 2, type = "blockingScalar" }

[servers."os/power-manager-ext"]
GetStatus = { id = 1, type = "blockingScalar" }
SetUsbBoost = { id = 2, type = "blockingScalar" }
SetOtgPriority = { id = 3, type = "scalar", cfg = "keyos" }
GetExtendedStatus = { id = 4, type = "blockingArchive" }
ClearChargeFault = { id = 5, type = "scalar" }
StatusSubscribe = { id = 6, type = "scalarEvent" }
SetBatteryPercent = { id = 20, type = "scalar", cfg = "not(keyos)" }
