// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Callbacks as CB } from "../../callbacks.slint";
import { SeedView, SeedViewType } from "../../types.slint";
import { Palette, Size, Importance, CallbackResult, ResultLevel } from "@ui/theme.slint";
import { IconButton, AppHeader, BasePage, PageBody, ScrollBody,
         ContentSection, ErrorModal, Dropdown,
         TitledInput, ButtonSection, Button } from "@ui/widgets.slint";
import { PasswordProps } from "./props.slint";
import { Navigate } from "../../gen/navigate.slint";
import { TR2, TrId } from "../../gen/tr.slint";

export component PasswordPage inherits BasePage {
    in property <PasswordProps> props;

    property <SeedView> new-seed: {
        seed-type: SeedViewType.password,
    };

    property <CallbackResult> result: { level: ResultLevel.info, success: true, text: "", title: "" };
    property <bool> has-errors: label-error || password-error;
    property <bool> label-error: true;
    property <bool> password-error: new-seed.password.password == "";
    property <bool> password-has-focus: password-input.has-focus;

    // Trigger auto-scroll when password input gains focus
    changed password-has-focus => {
        if (password-has-focus) {
            content-scroll.viewport-y = -150px;
        }
    }

    VerticalLayout {
        AppHeader {
            title: TR2.lookup(TrId.CreateItemTitle);

            IconButton {
                icon: "chevron-left";
                size: Size.sz8;
                importance: Importance.normal;
                clicked => {
                    Navigate.backward();
                }
            }
        }

        PageBody {
            p-x: Size.sz4;
            p-y: Size.sz4;

            content-scroll := ScrollBody {
                p-x: Size.zero;
                p-y: Size.zero;

                ContentSection {
                    Dropdown {
                        title: TR2.lookup(TrId.CreateItemType);
                        placeholder: TR2.lookup(TrId.CreateItemTypeTextFiller);
                        selected-index: 0;
                        locked: true;
                        model: [
                            {
                                label: CB.get-seed-name(SeedViewType.password),
                                value: "password",
                                icon: "pin",
                            },
                        ];
                    }

                    TitledInput {
                        title: TR2.lookup(TrId.CreateItemItemLabel);
                        placeholder: TR2.lookup(TrId.CreateItemItemLabelFillerText);
                        text: new-seed.label;
                        message: TR2.lookup(TrId.CreateItemSeedErrorsMissingField);
                        has-notice: self.message != "";
                        caps-mode: sentences;

                        edited(text) => {
                            new-seed.label = text;
                            self.message = CB.validate-new-label(text);
                            self.has-notice = self.message != "";
                            label-error = self.has-notice;
                        }
                    }

                    TitledInput {
                        title: TR2.lookup(TrId.CreateItemAccount);
                        placeholder: TR2.lookup(TrId.CreateItemAccountFillerText);
                        text: new-seed.password.account;
                        caps-mode: sentences;

                        edited(text) => {
                            new-seed.password.account = text;
                        }
                    }

                    password-input := TitledInput {
                        title: TR2.lookup(TrId.CreateItemPassword);
                        placeholder: TR2.lookup(TrId.CreateItemPasswordFillerText);
                        text: new-seed.password.password;
                        has-notice: self.text == "";
                        show-password: false;
                        input-type: InputType.password;

                        edited(text) => {
                            new-seed.password.password = text;
                            self.has-notice = text == "";
                            // TODO: potentially add warning copy
                            // if (self.has-notice) {
                            //     self.message = "Passwords must not be empty";
                            // } else {
                            //     self.message = "";
                            // }
                            password-error = self.has-notice;
                        }
                    }

                    // Conditional spacer for keyboard scrolling
                    if password-has-focus: Rectangle {
                        height: 250px;
                    }
                }
            }

            ButtonSection {
                save-button := Button {
                    label: TR2.lookup(TrId.CommonButtonSave);
                    enabled: !has-errors;
                    clicked => {
                        // Navigation is handled by rust code
                        new-seed.color = CB.get-default-color(new-seed.seed-type);
                        result = CB.save(new-seed);
                    }
                }
            }
        }
    }

    if !result.success: ErrorModal {
        icon: result.level == ResultLevel.info ? "info" : "alert";
        icon-color: result.level == ResultLevel.info ? Palette.content-brand : Palette.content-notice;
        title: result.title;
        text: result.text;
        confirm-button-label: TR2.lookup(TrId.CommonButtonConfirm);

        confirm-clicked => {
            result.success = true;
        }
    }
}
