# SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "nfc-ndef"
version = "0.1.0"
edition = "2021"
description = "NFC server test client"

[dependencies]
backup-shard = { workspace = true }
log = "0.4.14"
log-server = { package = "xous-api-log", path = "../../xous/api/log" }
ndef = { workspace = true }
nfc = { workspace = true }
server = { path = "../../server" }
xous = { path = "../../xous/xous-rs" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(keyos)'] }
