# SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Dependencies
on:
  workflow_call:
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  pass-security-audit:
    name: Pass security audit?
    runs-on: ubuntu-latest
    container:
      image: foundationdevices/keyos-build:latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Git Credentials via gh CLI
        run: |
          gh auth setup-git
      - run: |
          cargo audit

  are-versions-really-minimal:
    name: Are versions really minimal?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-nix-rust
      - run: |
          nix develop .#build --command cargo check --workspace \
                      -Z minimal-versions \
                      --exclude curve25519-dalek-loader \
                      --exclude ed25519-dalek-loader \
                      --exclude loader \
                      --exclude perflib \
                      --exclude sha2-loader \
                      --exclude skeleton \
                      --exclude gui-server \
                      --exclude gui-app-camera \
                      --exclude gui-app-control-center \
                      --exclude gui-app-keyboard \
                      --exclude gui-app-example-logo \
                      --exclude gui-app-example-widgets \
                      --exclude gui-app-test \
                      --exclude gui-app-qr-scanner \
                      --exclude gui-app-regulatory \
                      --exclude cryptoauthlib \
                      --exclude simulator \
                      --exclude atsama5d27 \
                      --exclude keyos-boot \
                      --exclude boot-common \
                      --exclude charge-boot \
                      --exclude crypto-client \
                      --exclude log-serial \
                      --exclude log-usb-serial \
                      --exclude usb-debug \
                      --exclude libblur \
                      --exclude keycard-auth-tool \
                      --exclude gui-app-recovery \
                      --exclude recovery-worker \
                      --exclude app-manager
        env:
          RUSTFLAGS: '--check-cfg=cfg(keyos)'
