// SPDX-License-Identifier: GPL-3.0-or-later
//
// Shared application state, held in a StoredValue<AppState> and threaded to
// every feature module (same ownership model as the Bitcoin app's AppState).

use std::collections::BTreeMap;

use decred_core::hd::ExtPubKey;
use decred_core::secp256k1::Secp256k1;
use slint_keyos_platform::slint::Weak;

use crate::keys::KeyError;
use crate::sign_tx::Origin;
// `AppWindow` is generated by the Slint build from ui/app.slint.
use crate::AppWindow;

pub struct AppState {
    ui: Weak<AppWindow>,
    /// One reusable secp256k1 context (signing + verification). Construction is
    /// expensive; build once and share.
    pub secp: Secp256k1<decred_core::secp256k1::All>,
    /// Handle to the secure element / settings surface. `Security::default()`
    /// is the same constructor the Bitcoin app uses.
    pub security: crate::Security,
    /// Default account index the UI is currently operating on (m/44'/42'/N').
    pub account: u32,
    /// BIP39 passphrase for the CURRENT session ("" = default wallet). Held in
    /// memory only, NEVER persisted; each distinct passphrase is a completely
    /// separate wallet derived from the same device seed. Zeroizing wipes the
    /// heap copy when it is replaced or the app exits (the transient copy
    /// inside the Slint text field is outside our reach).
    pub passphrase: zeroize::Zeroizing<String>,
    /// Persistent named-account list (index + name), loaded at startup.
    pub accounts: crate::account_store::AccountStore,
    /// Session cache of account-level extended PUBLIC keys for the current
    /// wallet (seed + passphrase). Public material only — it can derive
    /// addresses, never spend. Everything that doesn't sign (trustless
    /// review, receive addresses, watch-only export, wrong-wallet detection)
    /// reads from here, so the secure-element seed prompt fires at most once
    /// per account per session plus once per actual signature. MUST be
    /// cleared when the passphrase changes (see `reset_wallet_session`).
    xpubs: BTreeMap<u32, ExtPubKey>,
    /// The decoded-but-not-yet-signed package awaiting user approval, with the
    /// transport it arrived on. Raw CBOR bytes are kept (not the parsed struct)
    /// so the parse is re-validated at sign time.
    pending: Option<(Origin, Vec<u8>)>,
    /// Animated-QR parts (UR frames) for the most recently signed tx, read back
    /// by the DynamicQrCode via the `signed-qr-parts` callback.
    signed_parts: Vec<String>,
}

impl AppState {
    pub fn new(ui: Weak<AppWindow>) -> Self {
        let accounts = crate::account_store::AccountStore::load();
        AppState {
            ui,
            secp: Secp256k1::new(),
            security: crate::Security::default(),
            // Restore the last-active account so receive/sign/export pick up
            // where the user left off.
            account: accounts.active,
            passphrase: zeroize::Zeroizing::new(String::new()),
            accounts,
            xpubs: BTreeMap::new(),
            pending: None,
            signed_parts: Vec::new(),
        }
    }

    /// Upgrade the weak UI handle. Panics only if called after the window is
    /// gone, which cannot happen while a callback is running.
    pub fn ui(&self) -> AppWindow { self.ui.upgrade().expect("UI alive") }

    /// The account-level xpub for `account` in the current wallet, deriving
    /// (and prompting for seed access) only on first use per session.
    pub fn account_xpub(&mut self, account: u32) -> Result<ExtPubKey, KeyError> {
        if let Some(xpub) = self.xpubs.get(&account) {
            return Ok(*xpub);
        }
        let xpub = crate::keys::derive_account_xpub(&self.secp, &self.security, &self.passphrase, account)?;
        self.xpubs.insert(account, xpub);
        Ok(xpub)
    }

    /// Forget everything tied to the current wallet identity: cached xpubs,
    /// any pending sign request, and rendered signed-tx QR frames. Called when
    /// the passphrase changes — keys and packages from one wallet must never
    /// be visible in another.
    pub fn reset_wallet_session(&mut self) {
        self.xpubs.clear();
        self.pending = None;
        self.signed_parts.clear();
    }

    /// Stash a pending signing request (set at QR/SD ingest, cleared on sign).
    pub fn set_pending(&mut self, origin: Origin, bytes: Vec<u8>) { self.pending = Some((origin, bytes)); }

    /// Clone out the pending request for the approval step.
    pub fn pending(&self) -> Option<(Origin, Vec<u8>)> { self.pending.clone() }

    /// Drop any pending request (Reject / Cancel / after a successful sign).
    pub fn clear_pending(&mut self) { self.pending = None; }

    /// Store the animated-QR parts for the signed tx.
    pub fn set_signed_parts(&mut self, parts: Vec<String>) { self.signed_parts = parts; }

    /// Read the signed-tx QR parts (empty until a tx is signed).
    pub fn signed_qr_parts(&self) -> Vec<String> { self.signed_parts.clone() }
}
